// ESLint — intentionally minimal.
//
// One rule is enabled: react-hooks/rules-of-hooks. It catches the most common
// React crash in this stack — a hook called conditionally or after an early
// `return` — at author time, instead of as a cryptic "Minified React error
// #310 / #300" in production. typescript-eslint is here only as the parser so
// .ts/.tsx files parse; none of its rules are turned on. Nothing else is
// enabled, so the linter stays silent unless you actually break the Rules of
// Hooks.
//
// This runs automatically via vite-plugin-checker (see vite.config.ts): a
// violation shows as an overlay during `deepspace dev start` and fails the build
// during `deepspace deploy`. You can also run it on its own with `npm run lint`.
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

export default [
  // src/router.ts is generated by generouted and carries a blanket
  // `/* eslint-disable */`. Linting it produces only an "unused disable
  // directive" warning on every run, so ignore it — the linter should stay
  // silent unless there's a real Rules of Hooks violation.
  // `**/._*` covers macOS AppleDouble metadata files, which are binary and
  // otherwise hard-fail the lint with "Parsing error: Invalid character".
  // `.deepspace/**` holds Playwright artifacts (test-results, playwright-report)
  // that the test runner rotates while a lint may be scanning them.
  { ignores: ['dist/**', 'node_modules/**', '.wrangler/**', '.vite/**', '.deepspace/**', 'src/router.ts', '**/._*'] },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
    },
  },
]
